version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directory: /containers/video-finish
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directory: /containers/image-prep
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directory: /containers/audio-beat-sync
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directory: /containers/audio-mix
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directory: /containers/audio-master
    schedule:
      interval: weekly
