#!/usr/bin/env bash
# Start manifest-only module sidecars for the local homelab profile (M4 catalog dev).
# Writes MODULE_*_URL hints to dev/module-fleet.env (source before npm run dev).
# Portable bash (macOS ships 3.2; no associative arrays).
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
MANIFESTS="$ROOT/dev/manifests"
PIDS="$ROOT/dev/module-fleet.pids"
ENV_FILE="$ROOT/dev/module-fleet.env"

if [[ ! -d "$MANIFESTS" ]] || [[ -z "$(ls -A "$MANIFESTS"/*.json 2>/dev/null)" ]]; then
  echo "manifests missing; run: npm run module-manifests" >&2
  exit 1
fi

# name port (one module per line)
# CATALOG MODE. Every entry here is started by scripts/module-sidecar.ts, which serves
# GET /module.json and returns an honest error from /invoke, /poll and /cancel. That is the point of
# this fleet: it stands the CATALOG up (registry discovery, projection, pickers, hook panel) without
# needing GPU bindings or provider credentials.
#
# It does NOT make a module invocable. A module that must actually RUN has its own server script
# (chain-module-server.ts, cloud-keyframe-module-server.ts, local-gpu-module-server.ts, ...) and is
# started separately with real env. Do not read a populated picker here as proof that generation
# works -- that distinction cost the cf#129 gate a leg.
#
# THE MEMBERSHIP RULE, and it is not the same rule as "does a manifest exist" (local#291).
#
# A manifest-only sidecar stands in for the DISCOVERY of a module, so the fleet is honest only while
# every module it stands up is one a local install can actually have. The test is a compose SERVICE,
# in any profile: default, `cloud`, `satellites`, `localgpu`, `edge`. If no profile in compose.yaml
# can bring the module up, standing it up here fabricates a module for the registry to discover, and
# the panel (a projection of the registry) renders it as a working, configurable feature. That is the
# local#229 / local#223 / local#278 shape, and this list is where the third instance of it lived.
#
# finish-rife is NOT here, deliberately, and it is the one module that must not come back:
# vivijure-local ships no RIFE image and no local RIFE path (Conrad 2026-07-28; see
# docs/FINISH_BACKEND.md, src/modules/finish-backend.ts, .github/workflows/build-image.yml). It has
# no compose service in any profile, so the only thing behind its knobs was a RunPod call, on a panel
# whose premise is that RunPod is opt-in. RIFE stays available to an operator who wires it to RunPod
# explicitly (scripts/finish-module-server.ts, docs/FINISH_BACKEND.md); it is not part of the fleet a
# local install stands up by default. Fence: tests/finish-rife-not-local-291.test.ts.
read -r -d '' MODULE_PORTS <<'EOF' || true
keyframe 9101
local-gpu 9102
own-gpu 9103
finish-lipsync 9111
finish-upscale 9112
beat-sync 9120
audio-master 9121
film-titles 9130
subtitle 9131
dialogue-gen 9140
music-gen 9141
cast-image 9142
image-generate 9143
plan-enhance 9144
EOF

: >"$PIDS"
: >"$ENV_FILE"
echo "# generated by dev-module-fleet.sh" >>"$ENV_FILE"

while read -r name port; do
  [[ -z "$name" ]] && continue
  mf="$MANIFESTS/$name.json"
  [[ -f "$mf" ]] || continue
  npx tsx "$ROOT/scripts/module-sidecar.ts" "$port" "$mf" &
  echo $! >>"$PIDS"
  binding="MODULE_$(echo "$name" | tr '[:lower:]' '[:upper:]' | tr '-' '_')"
  echo "${binding}_URL=http://127.0.0.1:${port}" >>"$ENV_FILE"
  echo "started $name -> :$port ($binding)"
done <<<"$MODULE_PORTS"

echo ""
echo "Fleet env written to $ENV_FILE"
echo "  set -a; source $ENV_FILE; set +a; npm run dev"
echo "Stop: bash scripts/stop-module-fleet.sh"
