/**
 * Write reverse-proxy/sites.runtime.caddyfile from env / CLI flags.
 * Compose mounts this over the image default when the file exists.
 */
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import type { DnsProviderId } from "./dns-provider-detect.js";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
export const SITES_RUNTIME_PATH = join(ROOT, "reverse-proxy", "sites.runtime.caddyfile");

export type CaddyTlsMode = "dns" | "files" | "auto";

function tlsBlock(mode: CaddyTlsMode, provider: DnsProviderId | ""): string {
  if (mode === "files") {
    return `\ttls /certs/minio.pem /certs/minio.key\n`;
  }
  if (mode === "auto" || !provider) {
    return "";
  }
  switch (provider) {
    case "cloudflare":
      return `\ttls {\n\t\tdns cloudflare {env.CF_DNS_TOKEN}\n\t}\n`;
    case "route53":
      return (
        `\ttls {\n` +
        `\t\tdns route53 {\n` +
        `\t\t\taccess_key_id {env.AWS_ACCESS_KEY_ID}\n` +
        `\t\t\tsecret_access_key {env.AWS_SECRET_ACCESS_KEY}\n` +
        `\t\t\thosted_zone_id {env.AWS_HOSTED_ZONE_ID}\n` +
        `\t\t}\n` +
        `\t}\n`
      );
    case "digitalocean":
      return `\ttls {\n\t\tdns digitalocean {env.DO_AUTH_TOKEN}\n\t}\n`;
    case "googleclouddns":
      return (
        `\ttls {\n` +
        `\t\tdns googleclouddns {\n` +
        `\t\t\tgcp_project {env.GCP_PROJECT}\n` +
        `\t\t}\n` +
        `\t}\n`
      );
    case "hetzner":
      return `\ttls {\n\t\tdns hetzner {env.HETZNER_API_TOKEN}\n\t}\n`;
    case "ovh":
      return (
        `\ttls {\n` +
        `\t\tdns ovh {\n` +
        `\t\t\tendpoint {env.OVH_ENDPOINT}\n` +
        `\t\t\tapplication_key {env.OVH_APPLICATION_KEY}\n` +
        `\t\t\tapplication_secret {env.OVH_APPLICATION_SECRET}\n` +
        `\t\t\tconsumer_key {env.OVH_CONSUMER_KEY}\n` +
        `\t\t}\n` +
        `\t}\n`
      );
    default:
      return "";
  }
}

export function renderSitesCaddyfile(opts: {
  appHost: string;
  minioHost: string;
  provider: DnsProviderId | "";
  tlsMode: CaddyTlsMode;
}): string {
  const app = opts.appHost.trim();
  const minio = opts.minioHost.trim();
  if (!app) throw new Error("CADDY_APP_HOST (studio hostname) is required");
  if (!minio) throw new Error("CADDY_MINIO_HOST (MinIO hostname) is required");

  const studioTls =
    opts.tlsMode === "dns" && opts.provider
      ? tlsBlock("dns", opts.provider)
      : opts.tlsMode === "files"
        ? `\ttls /certs/studio.pem /certs/studio.key\n`
        : "";

  const minioTls = tlsBlock(opts.tlsMode === "auto" ? "dns" : opts.tlsMode, opts.provider);
  // Wildcard MinIO always needs DNS-01 or file certs; refuse empty auto without provider.
  if (opts.tlsMode !== "files" && !opts.provider) {
    throw new Error(
      "CADDY_DNS_PROVIDER is required for the MinIO wildcard cert (or set CADDY_TLS_MODE=files)",
    );
  }

  return (
    `# Generated by npm run install:edge / render-caddy-sites. Do not edit by hand.\n` +
    `# Studio control panel + API\n` +
    `${app} {\n` +
    studioTls +
    `\treverse_proxy studio:8790\n` +
    `}\n` +
    `\n` +
    `# MinIO S3 API + bucket subdomains (virtual-hosted style)\n` +
    `${minio}, *.${minio} {\n` +
    minioTls +
    `\treverse_proxy minio:9000\n` +
    `}\n`
  );
}

export function writeSitesRuntime(opts: {
  appHost: string;
  minioHost: string;
  provider: DnsProviderId | "";
  tlsMode: CaddyTlsMode;
}): string {
  const body = renderSitesCaddyfile(opts);
  mkdirSync(dirname(SITES_RUNTIME_PATH), { recursive: true });
  writeFileSync(SITES_RUNTIME_PATH, body, "utf8");
  return SITES_RUNTIME_PATH;
}

function readArg(name: string): string | undefined {
  const i = process.argv.indexOf(`--${name}`);
  if (i >= 0 && process.argv[i + 1]) return process.argv[i + 1];
  return undefined;
}

const isMain =
  Boolean(process.argv[1]) && fileURLToPath(import.meta.url) === resolve(process.argv[1]!);

if (isMain) {
  const appHost = readArg("app-host") ?? process.env.CADDY_APP_HOST ?? process.env.STUDIO_HOST ?? "";
  const minioHost =
    readArg("minio-host") ?? process.env.CADDY_MINIO_HOST ?? process.env.MINIO_HOST ?? "";
  const provider = (readArg("provider") ??
    process.env.CADDY_DNS_PROVIDER ??
    "") as DnsProviderId | "";
  const tlsMode = (readArg("tls-mode") ?? process.env.CADDY_TLS_MODE ?? "dns") as CaddyTlsMode;
  const path = writeSitesRuntime({ appHost, minioHost, provider, tlsMode });
  console.log(`wrote ${path}`);
}
