-- Vivijure Studio -- PUBLIC DEMO STUDIO seed (#625). DEMO D1 ONLY. NEVER prod.
--
-- This file lives under migrations/demo/ ON PURPOSE: like migrations/manual/, a subdirectory is NOT
-- scanned by `wrangler d1 migrations apply`, so it can NEVER auto-apply to the production DB and
-- pollute the real catalog / project library. The public demo deploy (AUTH_MODE=demo, its own demo
-- D1, no AI/RunPod/dispatch/R2 bindings) applies it EXPLICITLY, AFTER the base schema:
--   wrangler d1 migrations apply <demo-db>            # base schema: migrations/0001..0010
--   wrangler d1 execute <demo-db> --file=migrations/demo/0001_demo_seed.sql
--
-- What it seeds:
--   1. installed_modules: the 26 in-repo module manifests, captured VERBATIM from each module worker
--      GET /module.json. DISPLAY-ONLY by construction -- the script_name is demo-seed-<name>, which no
--      dispatch namespace serves (the demo binds none), and AUTH_MODE=demo denies every mutation at the
--      gate, so nothing here is invocable. The registry reads these rows in demo mode (#625 exception in
--      discoverDispatchModules) so GET /api/modules projects the AUTHENTIC studio catalog with zero mock
--      workers. Re-capture on module drift (a future reseed follow-up).
--   2. Demo content: browseable projects, cast, and COMPLETED renders whose films are the public S23
--      showcase MP4s. The render output_key is an ABSOLUTE assets.skyphusion.net URL, so the demo needs
--      NO R2 binding; the render display consumes it verbatim (planner-history-row.js artifactUrl).
--
-- Idempotent: every statement is INSERT OR IGNORE, so a re-apply is a no-op.

-- ---------------------------------------------------------------------------
-- installed_modules: the captured real catalog (display-only; see header).
-- ---------------------------------------------------------------------------
INSERT OR IGNORE INTO installed_modules (name, script_name, manifest_json, api, installed_at, enabled) VALUES
  ('alibaba-wan', 'demo-seed-alibaba-wan', '{"name":"alibaba-wan","version":"0.1.1","api":"vivijure-module/2","hooks":["motion.backend"],"provides":[{"id":"i2v-cloud","label":"Wan 2.6 (cloud i2v)"}],"config_schema":{"enable_prompt_expansion":{"type":"bool","default":false,"label":"expand prompt (off by default)"}},"ui":{"section":"motion","order":70,"locality":"cloud","cost":"Pay per render","blurb":"Rents datacenter GPUs by the second -- top quality, scale-to-zero; you pay only for render seconds."}}', 'vivijure-module/2', 1752000000, 1);
INSERT OR IGNORE INTO installed_modules (name, script_name, manifest_json, api, installed_at, enabled) VALUES
  ('alibaba-wan-lora', 'demo-seed-alibaba-wan-lora', '{"name":"alibaba-wan-lora","version":"0.1.1","api":"vivijure-module/2","hooks":["motion.backend"],"provides":[{"id":"i2v-cloud-lora","label":"Wan 2.2 (cloud i2v + custom LoRA)"}],"config_schema":{"high_noise_loras":{"type":"string","default":"[]","label":"high-noise LoRAs -- JSON [{path,scale}]"},"low_noise_loras":{"type":"string","default":"[]","label":"low-noise LoRAs -- JSON [{path,scale}]"},"seed":{"type":"int","default":-1,"min":-1,"label":"seed (-1 = random)"},"enable_safety_checker":{"type":"bool","default":true,"label":"safety checker"}},"ui":{"section":"motion","order":75,"locality":"cloud","cost":"Pay per render","blurb":"Rents datacenter GPUs by the second -- top quality, scale-to-zero; you pay only for render seconds."}}', 'vivijure-module/2', 1752000000, 1);
INSERT OR IGNORE INTO installed_modules (name, script_name, manifest_json, api, installed_at, enabled) VALUES
  ('audio-master', 'demo-seed-audio-master', '{"name":"audio-master","version":"0.1.1","api":"vivijure-module/2","hooks":["master"],"provides":[{"id":"master","label":"Master film audio (loudness + music upscale)"}],"config_schema":{"target_lufs":{"type":"float","default":-14,"min":-24,"max":-9,"label":"loudness target (LUFS)"},"upscale":{"type":"bool","default":true,"label":"music upscale (soxr 48k + air lift)"},"format":{"type":"enum","values":["wav","mp3"],"default":"wav","label":"output format"}},"ui":{"section":"master","icon":"sliders","order":10}}', 'vivijure-module/2', 1752000000, 1);
INSERT OR IGNORE INTO installed_modules (name, script_name, manifest_json, api, installed_at, enabled) VALUES
  ('beat-sync', 'demo-seed-beat-sync', '{"name":"beat-sync","version":"0.1.1","api":"vivijure-module/2","hooks":["score"],"provides":[{"id":"librosa-beat-sync","label":"Beat sync (librosa, fleet VPC)"}],"config_schema":{"clip_seconds":{"type":"float","default":8,"min":0.5,"max":60,"label":"target seconds per shot"},"mode":{"type":"enum","values":["beat","duration"],"default":"beat","label":"timing mode"},"min_scene_s":{"type":"float","default":2.5,"min":0.5,"max":30,"label":"minimum shot length (beat mode)"},"max_scene_s":{"type":"float","default":12,"min":1,"max":60,"label":"maximum shot length (beat mode)"},"force_shots":{"type":"int","default":0,"min":0,"max":50,"label":"force shot count (duration mode; 0 = auto)"}},"ui":{"section":"score","order":30}}', 'vivijure-module/2', 1752000000, 1);
INSERT OR IGNORE INTO installed_modules (name, script_name, manifest_json, api, installed_at, enabled) VALUES
  ('cast-image', 'demo-seed-cast-image', '{"name":"cast-image","version":"0.1.1","api":"vivijure-module/2","hooks":["cast.image"],"provides":[{"id":"cast-refs","label":"Training references (FLUX 2 / Nano Banana)"}],"config_schema":{"model":{"type":"enum","values":["@cf/black-forest-labs/flux-2-klein-9b","google/nano-banana-pro","@cf/black-forest-labs/flux-2-klein-4b","@cf/black-forest-labs/flux-2-dev"],"default":"@cf/black-forest-labs/flux-2-klein-9b","label":"image model"},"num_images":{"type":"int","default":10,"min":4,"max":10,"label":"training images"}},"ui":{"section":"cast","order":10}}', 'vivijure-module/2', 1752000000, 1);
INSERT OR IGNORE INTO installed_modules (name, script_name, manifest_json, api, installed_at, enabled) VALUES
  ('cloud-keyframe', 'demo-seed-cloud-keyframe', '{"name":"cloud-keyframe","version":"0.1.1","api":"vivijure-module/2","hooks":["keyframe"],"provides":[{"id":"cloud-keyframe","label":"Cloud Keyframe (reference-conditioned, GPUless)"}],"config_schema":{"model":{"type":"enum","values":["@cf/black-forest-labs/flux-2-klein-9b","google/nano-banana-pro","@cf/black-forest-labs/flux-2-klein-4b","@cf/black-forest-labs/flux-2-dev"],"default":"@cf/black-forest-labs/flux-2-klein-9b","label":"image model (FLUX-2 klein-9b cheap/fast; nano-banana-pro quality)"},"width":{"type":"int","default":1344,"min":512,"max":1536,"label":"width"},"height":{"type":"int","default":768,"min":512,"max":1536,"label":"height"},"refs_per_slot":{"type":"int","default":1,"min":1,"max":4,"label":"reference images per character"}},"ui":{"section":"keyframe","order":20}}', 'vivijure-module/2', 1752000000, 1);
INSERT OR IGNORE INTO installed_modules (name, script_name, manifest_json, api, installed_at, enabled) VALUES
  ('dialogue-gen', 'demo-seed-dialogue-gen', '{"name":"dialogue-gen","version":"0.1.1","api":"vivijure-module/2","hooks":["dialogue"],"provides":[{"id":"aura1","label":"Dialogue voices (Deepgram Aura-1)"}],"ui":{"section":"dialogue","icon":"mic","order":10}}', 'vivijure-module/2', 1752000000, 1);
INSERT OR IGNORE INTO installed_modules (name, script_name, manifest_json, api, installed_at, enabled) VALUES
  ('film-titles', 'demo-seed-film-titles', '{"name":"film-titles","version":"0.1.1","api":"vivijure-module/2","hooks":["film.finish"],"provides":[{"id":"film-titles","label":"Title + credit cards on the finished film"}],"config_schema":{"font":{"type":"string","default":"DejaVu Sans","label":"card font (installed in the video-finish container)"},"color":{"type":"string","default":"white","label":"card text color (name or #rrggbb)"},"bg":{"type":"string","default":"black","label":"card background color"},"title_seconds":{"type":"int","default":3,"min":1,"max":15,"label":"title card duration (s)"},"credit_seconds":{"type":"int","default":5,"min":1,"max":30,"label":"credit card duration (s)"}},"ui":{"section":"film.finish","order":10}}', 'vivijure-module/2', 1752000000, 1);
INSERT OR IGNORE INTO installed_modules (name, script_name, manifest_json, api, installed_at, enabled) VALUES
  ('finish-lipsync', 'demo-seed-finish-lipsync', '{"name":"finish-lipsync","version":"0.1.4","api":"vivijure-module/2","hooks":["finish"],"provides":[{"id":"lipsync","label":"Lip-sync to dialogue (MuseTalk)"}],"config_schema":{"version":{"type":"enum","values":["v15","v1"],"default":"v15","label":"MuseTalk version (v15 = v1.5, best)"},"bbox_shift":{"type":"int","default":0,"min":-20,"max":20,"label":"mouth crop shift"}},"ui":{"section":"finish","icon":"mic","order":15},"finish_artifacts":{"output_key":{"kind":"append_suffix","suffix":"_ls"},"applied":[{"tag":"lipsync:{version|v15}"}]},"finish_consumes_audio":true}', 'vivijure-module/2', 1752000000, 1);
INSERT OR IGNORE INTO installed_modules (name, script_name, manifest_json, api, installed_at, enabled) VALUES
  ('finish-rife', 'demo-seed-finish-rife', '{"name":"finish-rife","version":"0.1.1","api":"vivijure-module/2","hooks":["finish"],"provides":[{"id":"interpolate","label":"Smooth motion (RIFE frame interpolation)"},{"id":"face_restore","label":"Relock faces (GFPGAN)"}],"config_schema":{"interpolate":{"type":"bool","default":true,"label":"smooth motion"},"interpolation_factor":{"type":"int","default":2,"min":1,"max":8,"label":"smoothness","enum_labels":{"1":"off","2":"2x","4":"4x","8":"8x"}},"face_restore":{"type":"enum","values":["none","gfpgan","codeformer"],"default":"none","label":"face restore"},"face_fidelity":{"type":"float","default":0.7,"min":0,"max":1,"label":"fidelity (0 = max restore, 1 = max fidelity)"},"only_faces":{"type":"bool","default":true,"label":"faces only (leave background untouched)"}},"ui":{"section":"finish","icon":"wand","order":10},"finish_artifacts":{"output_key":{"kind":"shot_named","filename":"_finished.mp4"},"applied":[{"when":{"knob":"interpolate","equals":false},"tag":"noop:interpolate-off"},{"tag":"interpolate:{interpolation_factor|2}x"}]}}', 'vivijure-module/2', 1752000000, 1);
INSERT OR IGNORE INTO installed_modules (name, script_name, manifest_json, api, installed_at, enabled) VALUES
  ('finish-upscale', 'demo-seed-finish-upscale', '{"name":"finish-upscale","version":"0.1.3","api":"vivijure-module/2","hooks":["finish"],"provides":[{"id":"upscale","label":"Upscale resolution (Real-ESRGAN)"}],"config_schema":{"scale":{"type":"int","default":2,"min":2,"max":4,"label":"upscale factor","enum_labels":{"2":"2x","4":"4x"}},"model":{"type":"enum","values":["realesr-animevideov3","RealESRGAN_x4plus"],"default":"realesr-animevideov3","label":"model"}},"ui":{"section":"finish","icon":"expand","order":20},"finish_artifacts":{"output_key":{"kind":"append_suffix","suffix":"_up"},"applied":[{"tag":"upscale:{scale|2}x"}]}}', 'vivijure-module/2', 1752000000, 1);
INSERT OR IGNORE INTO installed_modules (name, script_name, manifest_json, api, installed_at, enabled) VALUES
  ('google-veo', 'demo-seed-google-veo', '{"name":"google-veo","version":"0.1.1","api":"vivijure-module/2","hooks":["motion.backend"],"provides":[{"id":"i2v-cloud","label":"Google Veo 3.1 Fast (cloud i2v)"}],"config_schema":{"generate_audio":{"type":"bool","default":false,"label":"native audio (off: core mux chain owns audio)"}},"ui":{"section":"motion","order":50,"locality":"cloud","cost":"Pay per render","blurb":"Rents datacenter GPUs by the second -- top quality, scale-to-zero; you pay only for render seconds."}}', 'vivijure-module/2', 1752000000, 1);
INSERT OR IGNORE INTO installed_modules (name, script_name, manifest_json, api, installed_at, enabled) VALUES
  ('keyframe', 'demo-seed-keyframe', '{"name":"keyframe","version":"0.2.1","api":"vivijure-module/2","hooks":["keyframe"],"provides":[{"id":"gpu-keyframe","label":"GPU Keyframe (SDXL on RunPod)"}],"config_schema":{"quality_tier":{"type":"enum","values":["draft","standard","final"],"default":"final","label":"quality tier"},"width":{"type":"int","default":1344,"min":512,"max":1536,"label":"width"},"height":{"type":"int","default":768,"min":512,"max":1536,"label":"height"},"steps":{"type":"int","default":30,"min":1,"max":60,"label":"diffusion steps"},"guidance_scale":{"type":"float","default":6.5,"min":0,"max":20,"label":"guidance scale"},"seed":{"type":"int","default":-1,"min":-1,"label":"seed (-1 = random)"}},"ui":{"section":"keyframe","order":10},"cancelable":true,"keyframe_label":"SDXL"}', 'vivijure-module/2', 1752000000, 1);
INSERT OR IGNORE INTO installed_modules (name, script_name, manifest_json, api, installed_at, enabled) VALUES
  ('kling', 'demo-seed-kling', '{"name":"kling","version":"0.1.1","api":"vivijure-module/2","hooks":["motion.backend"],"provides":[{"id":"i2v-cloud","label":"Kling V2.1 Pro (cloud i2v)"}],"config_schema":{"guidance_scale":{"type":"float","default":0.5,"min":0,"max":1,"label":"guidance scale"},"negative_prompt":{"type":"string","default":"","label":"negative prompt"},"enable_safety_checker":{"type":"bool","default":true,"label":"safety checker"}},"ui":{"section":"motion","order":20,"locality":"cloud","cost":"Pay per render","blurb":"Rents datacenter GPUs by the second -- top quality, scale-to-zero; you pay only for render seconds."}}', 'vivijure-module/2', 1752000000, 1);
INSERT OR IGNORE INTO installed_modules (name, script_name, manifest_json, api, installed_at, enabled) VALUES
  ('local-gpu', 'demo-seed-local-gpu', '{"name":"local-gpu","version":"0.1.1","api":"vivijure-module/2","hooks":["motion.backend"],"provides":[{"id":"i2v-local-gpu","label":"Local GPU (image-to-video on your own card)"}],"config_schema":{"quality":{"type":"enum","values":["draft","standard","final"],"default":"standard","label":"quality"},"fps":{"type":"int","default":24,"min":8,"max":30,"label":"fps (backend may pin its own; e.g. CogVideoX = 8)"},"flow_shift":{"type":"float","default":5,"min":1,"max":12,"label":"motion (flow shift; LTX door only, ignored otherwise)"},"negative_prompt":{"type":"string","default":"","label":"negative prompt (additive)"},"seed":{"type":"int","default":-1,"min":-1,"label":"seed (-1 = random)"}},"ui":{"section":"motion","order":4,"locality":"local","cost":"Free after hardware","blurb":"Renders on your own GPU -- no cloud, no per-render cost; quality scales with your card and chosen backend (12GB LTX floor, 16GB CogVideoX).","limits":["Runs whichever local backend you point it at: LTX (12GB floor) or CogVideoX (16GB floor); bigger cards add headroom","Short i2v clips (draft / standard / final tiers); resolution + cadence set by the backend","One clip at a time (a consumer card runs a single i2v job)"]},"cancelable":true}', 'vivijure-module/2', 1752000000, 1);
INSERT OR IGNORE INTO installed_modules (name, script_name, manifest_json, api, installed_at, enabled) VALUES
  ('minimax-hailuo', 'demo-seed-minimax-hailuo', '{"name":"minimax-hailuo","version":"0.1.1","api":"vivijure-module/2","hooks":["motion.backend"],"provides":[{"id":"i2v-cloud","label":"MiniMax Hailuo 2.3 Fast (cloud i2v)"}],"config_schema":{"enable_prompt_expansion":{"type":"bool","default":true,"label":"expand prompt"},"go_fast":{"type":"bool","default":true,"label":"fast mode"}},"ui":{"section":"motion","order":40,"locality":"cloud","cost":"Pay per render","blurb":"Rents datacenter GPUs by the second -- top quality, scale-to-zero; you pay only for render seconds."}}', 'vivijure-module/2', 1752000000, 1);
INSERT OR IGNORE INTO installed_modules (name, script_name, manifest_json, api, installed_at, enabled) VALUES
  ('music-gen', 'demo-seed-music-gen', '{"name":"music-gen","version":"0.1.1","api":"vivijure-module/2","hooks":["score"],"provides":[{"id":"minimax-music","label":"MiniMax Music 2.6 (Workers AI)"}],"config_schema":{"prompt":{"type":"string","default":"","label":"music prompt (blank = derive from storyboard)"},"lyrics":{"type":"string","default":"","label":"lyrics (optional; blank uses [Instrumental] unless auto-generating)"},"is_instrumental":{"type":"bool","default":true,"label":"instrumental (no vocals)"},"lyrics_optimizer":{"type":"bool","default":false,"label":"auto-generate lyrics from prompt"},"format":{"type":"enum","values":["mp3","wav"],"default":"mp3","label":"audio format"},"bitrate":{"type":"enum","values":["32000","64000","128000","256000"],"default":"128000","label":"bitrate"},"sample_rate":{"type":"enum","values":["16000","24000","32000","44100"],"default":"44100","label":"sample rate"}},"ui":{"section":"score","order":10}}', 'vivijure-module/2', 1752000000, 1);
INSERT OR IGNORE INTO installed_modules (name, script_name, manifest_json, api, installed_at, enabled) VALUES
  ('narration-gen', 'demo-seed-narration-gen', '{"name":"narration-gen","version":"0.2.1","api":"vivijure-module/2","hooks":["score"],"provides":[{"id":"minimax-speech","label":"MiniMax Speech 02 HD (RunPod)"}],"config_schema":{"text":{"type":"string","default":"","label":"narration script (blank = derive from storyboard)"},"voice_id":{"type":"string","default":"Wise_Woman","label":"voice id"},"emotion":{"type":"enum","values":["happy","sad","angry","fearful","disgusted","surprised","neutral"],"default":"neutral","label":"emotion"},"format":{"type":"enum","values":["mp3","flac","wav"],"default":"mp3","label":"audio format"},"pitch":{"type":"int","default":0,"min":-12,"max":12,"label":"pitch"},"speed":{"type":"float","default":1,"min":0.5,"max":2,"label":"speed"},"volume":{"type":"float","default":1,"min":0,"max":10,"label":"volume"},"sample_rate":{"type":"enum","values":["8000","16000","22050","24000","32000","44100"],"default":"44100","label":"sample rate"}},"ui":{"section":"score","order":20}}', 'vivijure-module/2', 1752000000, 1);
INSERT OR IGNORE INTO installed_modules (name, script_name, manifest_json, api, installed_at, enabled) VALUES
  ('notify-email', 'demo-seed-notify-email', '{"name":"notify-email","version":"0.1.0","api":"vivijure-module/2","hooks":["notify"],"provides":[{"id":"notify-email","label":"Email notification (Cloudflare Email Service)"}],"config_schema":{"notify_email":{"type":"string","default":"","label":"Notify email address (render-done mail recipient)","scope":"install"}},"ui":{"section":"notify","order":10}}', 'vivijure-module/2', 1752000000, 1);
INSERT OR IGNORE INTO installed_modules (name, script_name, manifest_json, api, installed_at, enabled) VALUES
  ('own-gpu', 'demo-seed-own-gpu', '{"name":"own-gpu","version":"0.1.1","api":"vivijure-module/2","hooks":["motion.backend"],"provides":[{"id":"i2v-own-gpu","label":"Own GPU (Wan2.2 i2v)"}],"config_schema":{"quality":{"type":"enum","values":["draft","standard","final"],"default":"standard","label":"quality"},"fps":{"type":"int","default":16,"min":8,"max":30,"label":"fps"},"flow_shift":{"type":"float","default":5,"min":1,"max":12,"label":"motion (flow shift, lower = faster)"},"negative_prompt":{"type":"string","default":"","label":"negative prompt (additive)"},"seed":{"type":"int","default":-1,"min":-1,"label":"seed (-1 = random)"}},"ui":{"section":"motion","order":5,"locality":"byo","cost":"Own keys (your RunPod endpoint)","blurb":"Renders on your own RunPod GPU endpoint -- own keys, no per-render markup; quality follows the GPU tier you rent."}}', 'vivijure-module/2', 1752000000, 1);
INSERT OR IGNORE INTO installed_modules (name, script_name, manifest_json, api, installed_at, enabled) VALUES
  ('plan-enhance', 'demo-seed-plan-enhance', '{"name":"plan-enhance","version":"0.2.1","api":"vivijure-module/2","hooks":["plan.enhance"],"provides":[{"id":"auto-direction","label":"Opus auto-direction"}],"config_schema":{"intensity":{"type":"enum","values":["light","medium","bold"],"default":"medium","label":"direction intensity"}},"ui":{"section":"plan","order":10}}', 'vivijure-module/2', 1752000000, 1);
INSERT OR IGNORE INTO installed_modules (name, script_name, manifest_json, api, installed_at, enabled) VALUES
  ('seedance', 'demo-seed-seedance', '{"name":"seedance","version":"0.2.2","api":"vivijure-module/2","hooks":["motion.backend"],"provides":[{"id":"i2v-cloud","label":"Seedance V1.5 Pro (cloud i2v)"}],"config_schema":{"resolution":{"type":"enum","values":["480p","720p"],"default":"720p","label":"resolution"},"aspect_ratio":{"type":"enum","values":["16:9","9:16","1:1"],"default":"16:9","label":"aspect ratio"},"camera_fixed":{"type":"bool","default":false,"label":"lock camera"},"generate_audio":{"type":"bool","default":false,"label":"generate audio"},"seed":{"type":"int","default":-1,"min":-1,"label":"seed (-1 = random)"}},"ui":{"section":"motion","order":10,"locality":"cloud","cost":"Pay per render","blurb":"Rents datacenter GPUs by the second -- top quality, scale-to-zero; you pay only for render seconds."}}', 'vivijure-module/2', 1752000000, 1);
INSERT OR IGNORE INTO installed_modules (name, script_name, manifest_json, api, installed_at, enabled) VALUES
  ('speech-upscale', 'demo-seed-speech-upscale', '{"name":"speech-upscale","version":"0.1.1","api":"vivijure-module/2","hooks":["speech"],"provides":[{"id":"speech-upscale","label":"Clean dialogue audio (resemble-enhance)"}],"config_schema":{"enable":{"type":"bool","default":false,"label":"enhance dialogue audio (opt-in)"},"denoise":{"type":"bool","default":false,"label":"extra denoise pass"}},"ui":{"section":"speech","icon":"wand","order":10}}', 'vivijure-module/2', 1752000000, 1);
INSERT OR IGNORE INTO installed_modules (name, script_name, manifest_json, api, installed_at, enabled) VALUES
  ('subtitle', 'demo-seed-subtitle', '{"name":"subtitle","version":"0.1.1","api":"vivijure-module/2","hooks":["film.finish"],"provides":[{"id":"subtitle","label":"Time-synced dialogue captions (burned-in + .srt)"}],"config_schema":{"enabled":{"type":"bool","default":true,"label":"burn captions onto the finished film"},"mode":{"type":"enum","values":["burn","sidecar","both"],"default":"burn","label":"burned-in, soft .srt sidecar, or both"},"font":{"type":"string","default":"DejaVu Sans","label":"caption font (installed in the video-finish container)"},"font_size":{"type":"int","default":28,"min":8,"max":120,"label":"caption font size (px)"},"color":{"type":"string","default":"white","label":"caption text color (white / black / yellow, or ASS &HBBGGRR)"},"position":{"type":"enum","values":["bottom","top","middle"],"default":"bottom","label":"caption position"},"box_style":{"type":"enum","values":["outline","box"],"default":"outline","label":"outline text or opaque box behind it"},"margin_v":{"type":"int","default":36,"min":0,"max":400,"label":"vertical margin from the frame edge (px)"}},"ui":{"section":"film.finish","order":5}}', 'vivijure-module/2', 1752000000, 1);
INSERT OR IGNORE INTO installed_modules (name, script_name, manifest_json, api, installed_at, enabled) VALUES
  ('text-overlay', 'demo-seed-text-overlay', '{"name":"text-overlay","version":"0.1.1","api":"vivijure-module/2","hooks":["finish"],"provides":[{"id":"text-overlay","label":"Text overlay (titles / credits / subtitles)"}],"config_schema":{"font":{"type":"string","default":"DejaVu Sans","label":"default font (must be installed in the video-finish container)"},"size":{"type":"int","default":48,"min":8,"max":400,"label":"default font size (px)"},"color":{"type":"string","default":"white","label":"default font color (name or #rrggbb)"},"safe_margin":{"type":"int","default":50,"min":0,"max":500,"label":"safe margin (px from edge)"}},"ui":{"section":"finish","order":20}}', 'vivijure-module/2', 1752000000, 1);
INSERT OR IGNORE INTO installed_modules (name, script_name, manifest_json, api, installed_at, enabled) VALUES
  ('vidu-q3', 'demo-seed-vidu-q3', '{"name":"vidu-q3","version":"0.1.1","api":"vivijure-module/2","hooks":["motion.backend"],"provides":[{"id":"i2v-cloud","label":"Vidu Q3 (cloud i2v)"}],"config_schema":{"generate_audio":{"type":"bool","default":false,"label":"native audio (off: core mux chain owns audio)"},"bgm":{"type":"bool","default":false,"label":"background music (off by default)"}},"ui":{"section":"motion","order":60,"locality":"cloud","cost":"Pay per render","blurb":"Rents datacenter GPUs by the second -- top quality, scale-to-zero; you pay only for render seconds."}}', 'vivijure-module/2', 1752000000, 1);
-- ---------------------------------------------------------------------------
-- Demo content: browseable projects, cast, and completed renders whose films
-- are the public S23 showcase MP4s (absolute URLs on assets.skyphusion.net, so
-- the demo needs NO R2 binding). High explicit ids (>=9000) keep the seed clear
-- of any real autoincrement rows. All INSERT OR IGNORE (idempotent re-apply).
-- ---------------------------------------------------------------------------

-- Projects (storyboard_projects): each carries a real storyboard so the planner resumes into it.
INSERT OR IGNORE INTO storyboard_projects (id, public_id, slug, name, prefs_json, last_storyboard_json) VALUES
  (9001, 'demo0001-0000-4000-8000-000000000001', 'neon-halflife', 'NEON AFTERGLOW', '{}',
   '{"title":"NEON AFTERGLOW","duration_seconds":30,"clip_seconds":3,"style_prefix":"1080p anime cyberpunk, rain-slick neon streets, cel shading, dramatic rim light","use_characters":["A","B"],"scenes":[{"id":"shot_01","prompt":"A lone courier in a worn flight jacket steps off a maglev platform into neon rain, holograms flickering overhead","character_slots":["A"],"target_seconds":3},{"id":"shot_02","prompt":"Close on the courier eyes reflecting a scrolling wall of advertisements","character_slots":["A"],"target_seconds":3},{"id":"shot_03","prompt":"A masked broker leans against a ramen stall, steam curling between them","character_slots":["B"],"target_seconds":3},{"id":"shot_04","prompt":"The two figures face off across the wet alley as drones sweep past","character_slots":["A","B"],"target_seconds":3},{"id":"shot_05","prompt":"Wide shot of the city skyline as the courier sprints across a rooftop, sirens blooming below","character_slots":["A"],"target_seconds":3}]}'),
  (9002, 'demo0002-0000-4000-8000-000000000002', 'fur-and-circuits', 'FUR AND CIRCUITS', '{}',
   '{"title":"FUR AND CIRCUITS","duration_seconds":24,"clip_seconds":3,"style_prefix":"warm storybook animation, red-lit cobblestone street, soft volumetric light","use_characters":["A","B"],"scenes":[{"id":"shot_01","prompt":"A small fox in a tailored coat trots down a cobblestone lane at dusk","character_slots":["A"],"target_seconds":3},{"id":"shot_02","prompt":"A brass automaton tips its hat to the fox beneath a flickering gas lamp","character_slots":["B"],"target_seconds":3},{"id":"shot_03","prompt":"The two walk side by side, shop windows glowing amber","character_slots":["A","B"],"target_seconds":3},{"id":"shot_04","prompt":"They pause on a bridge as the first stars appear over the rooftops","character_slots":["A","B"],"target_seconds":3}]}'),
  (9003, 'demo0003-0000-4000-8000-000000000003', 'rust', 'RUST', '{}',
   '{"title":"RUST","duration_seconds":9,"clip_seconds":3,"style_prefix":"weathered industrial realism, overcast light, rust and moss","use_characters":["A","B"],"scenes":[{"id":"shot_01","prompt":"A tall salvage robot pries open a collapsed bulkhead in a flooded yard","character_slots":["A"],"target_seconds":3,"dialogue":{"slot":"A","text":"I told you it would still be here."}},{"id":"shot_02","prompt":"A smaller companion robot rolls up carrying a cracked solar panel","character_slots":["B"],"target_seconds":3},{"id":"shot_03","prompt":"The two robots shake hands as sparks drift in the grey air","character_slots":["A","B"],"target_seconds":3}]}');

-- Cast (cast_members): named characters with a bible, a ready LoRA, and a portrait. portrait_key is an
-- ABSOLUTE assets.skyphusion.net URL (same binding-free pattern as the render output_key below), so the
-- demo needs NO R2 binding; cast.js artifactUrl returns an absolute key verbatim. portrait_mime image/jpeg.
INSERT OR IGNORE INTO cast_members (id, public_id, slug, name, bible, portrait_key, portrait_mime, lora_status, lora_trained_at) VALUES
  (9101, 'demo0101-0000-4000-8000-000000000101', 'kesh', 'Kesh', 'A neon-lit courier who runs data between arcologies. Calm, precise, haunted by a job that went wrong.', 'https://assets.skyphusion.net/vivijure/showcase/cast/kesh.jpg', 'image/jpeg', 'ready', '2026-07-01 00:00:00'),
  (9102, 'demo0102-0000-4000-8000-000000000102', 'the-broker', 'The Broker', 'A masked information broker who trades in secrets on the wet side of the city.', 'https://assets.skyphusion.net/vivijure/showcase/cast/the-broker.jpg', 'image/jpeg', 'ready', '2026-07-01 00:00:00'),
  (9103, 'demo0103-0000-4000-8000-000000000103', 'salvage-robot', 'Salvage Robot', 'A tall reclamation unit built to open what the flood sealed. Patient and stubborn.', 'https://assets.skyphusion.net/vivijure/showcase/cast/salvage-robot.jpg', 'image/jpeg', 'ready', '2026-07-01 00:00:00'),
  (9104, 'demo0104-0000-4000-8000-000000000104', 'companion-robot', 'Companion Robot', 'A small wheeled helper robot with a cracked chassis and boundless optimism.', 'https://assets.skyphusion.net/vivijure/showcase/cast/companion-robot.jpg', 'image/jpeg', 'ready', '2026-07-01 00:00:00');

-- Renders (renders): COMPLETED films. output_key is an ABSOLUTE showcase URL; the render display
-- (planner-history-row.js artifactUrl helper) uses it verbatim instead of prefixing /api/artifact/.
INSERT OR IGNORE INTO renders (id, public_id, job_id, project, project_id, quality_tier, status, submitted_at, updated_at, completed_at, output_key, output_json, label, mode, execution_time_ms) VALUES
  (9201, 'demo0201-0000-4000-8000-000000000201', 'demo-neon-halflife', 'NEON AFTERGLOW', 9001, 'final', 'COMPLETED', 1751990000, 1751991500, 1751991500, 'https://assets.skyphusion.net/vivijure/showcase/neon-halflife-run1.mp4', '{"seconds":30,"shots":10,"note":"demo showcase film"}', 'NEON AFTERGLOW', 'full', 1500000),
  (9202, 'demo0202-0000-4000-8000-000000000202', 'demo-fur-and-circuits', 'FUR AND CIRCUITS', 9002, 'final', 'COMPLETED', 1751980000, 1751981200, 1751981200, 'https://assets.skyphusion.net/vivijure/showcase/fur-and-circuits-scored.mp4', '{"seconds":24,"shots":8,"note":"demo showcase film, scored"}', 'FUR AND CIRCUITS', 'full', 1200000),
  (9203, 'demo0203-0000-4000-8000-000000000203', 'demo-rust', 'RUST', 9003, 'final', 'COMPLETED', 1751970000, 1751970600, 1751970600, 'https://assets.skyphusion.net/vivijure/showcase/rust-narrated.mp4', '{"seconds":9,"shots":3,"note":"demo showcase film, narrated"}', 'RUST', 'full', 600000),
  (9204, 'demo0204-0000-4000-8000-000000000204', 'demo-vivijure-speaks', 'NEON AFTERGLOW', 9001, 'final', 'COMPLETED', 1751960000, 1751960300, 1751960300, 'https://assets.skyphusion.net/vivijure/showcase/vivijure-speaks.mp4', '{"seconds":3,"shots":2,"note":"demo showcase film, talking character lip-synced and upscaled"}', 'Vivijure Speaks', 'full', 300000);
